############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "About CBorg"
pageRef = "/about"
parent = "About"
weight = 2

[[main]]
name = "FAQ"
pageRef = "/faq"
parent = "About"
weight = 6

[[main]]
name = "News"
pageRef = "/news"
weight = 3

[[main]]
name = "Models"
pageRef = "/models"
weight = 4

[[main]]
name = "Benchmarks"
pageRef = "/benchmarks"
weight = 5

[[main]]
name = "SciCode"
pageRef = "/bench_scicode"
parent = "Benchmarks"
weight = -1

[[main]]
name = "Coding"
pageRef = "/tools"
weight = 6

[[main]]
name = "Getting Started"
pageRef = "/tools_ai_101"
parent = "Coding"
weight = -10

[[main]]
name = "Continue (VS Code)"
parent = "Coding"
pageRef = "/tools_continue"
weight = -8

[[main]]
name = "Cline (VS Code)"
parent = "Coding"
pageRef = "/tools_cline"
weight = -6

[[main]]
name = "Roo Code (VS Code)"
parent = "Coding"
pageRef = "/tools_roo"
weight = -9

[[main]]
name = "Aider"
parent = "Coding"
pageRef = "/tools_aider"
weight = -6

[[main]]
name = "RStudio (gptstudio)"
parent = "Coding"
pageRef = "/tools_rstudio"
weight = 2

[[main]]
name = "Gemini CLI"
parent = "Coding"
pageRef = "/tools_geminicli"
weight = -6

[[main]]
name = "Codex CLI"
parent = "Coding"
pageRef = "/tools_codex"
weight = -6

[[main]]
name = "ClaudeCode"
parent = "Coding"
pageRef = "/tools_claudecode"
weight = -7

[[main]]
name = "JupyterLab"
parent = "Coding"
pageRef = "/tools_jupyter"
weight = 1

[[main]]
name = "Cursor"
parent = "Coding"
pageRef = "/tools_cursor"
weight = -4 

[[main]]
name = "CBorg Client Proxy"
parent = "Coding"
pageRef = "/tools_cborgproxy"
weight = 10

[[main]]
weight = 7
name = "API"

[[main]]
parent = "API"
weight = 1
name = "API Examples"
pageRef = "/api_examples"

[[main]]
parent = "API"
weight = 1
name = "API FAQ"
pageRef = "/api_faq"

[[main]]
parent = "API"
weight = 2
name = "Request API Key"
pageRef = "/api_request"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
